### ISSUE TITLE
Add issue and PR template

### ISSUE THREAD

**Issue by prateekiiest** [prateekiiest/boston_housing#4]

**Comment by anshumanv** [comment]
I'll do this, since I have them ready

**Comment by egin10** [comment]
what is this problem ?

**Comment by saisankargochhayat** [comment]
Let me add that!

**Comment by Priyansh2** [comment]
@prateekiiest can you elaborate on the problem , what do you want ?

**Comment by prateekiiest** [comment]
Every project has some guidelines on what are the good practices about creating a Pull Request or opening a new issue.

**Comment by prateekiiest** [comment]
@saisankargochhayat  are you working on it?
